package com.zy.dsdt.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BLANK_QUESTION_P.
 */
public class BlankQuestionP {

    private String bno;
    private String bstem;
    private String bsanalysis;
    private Integer bchapter;
    private String banswers;

    public BlankQuestionP() {
    }

    public BlankQuestionP(String bno) {
        this.bno = bno;
    }

    public BlankQuestionP(String bno, String bstem, String bsanalysis, Integer bchapter, String banswers) {
        this.bno = bno;
        this.bstem = bstem;
        this.bsanalysis = bsanalysis;
        this.bchapter = bchapter;
        this.banswers = banswers;
    }

    public String getBno() {
        return bno;
    }

    public void setBno(String bno) {
        this.bno = bno;
    }

    public String getBstem() {
        return bstem;
    }

    public void setBstem(String bstem) {
        this.bstem = bstem;
    }

    public String getBsanalysis() {
        return bsanalysis;
    }

    public void setBsanalysis(String bsanalysis) {
        this.bsanalysis = bsanalysis;
    }

    public Integer getBchapter() {
        return bchapter;
    }

    public void setBchapter(Integer bchapter) {
        this.bchapter = bchapter;
    }

    public String getBanswers() {
        return banswers;
    }

    public void setBanswers(String banswers) {
        this.banswers = banswers;
    }

}
