package com.zy.dsdt.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHOICE_QUESTION.
 */
public class ChoiceQuestion {

    private String chno;
    private String chstem;
    private String chanalysis;
    private Integer chchapter;
    private Integer chanswer;
    private String chA;
    private String chB;
    private String chC;
    private String chD;

    public ChoiceQuestion() {
    }

    public ChoiceQuestion(String chno) {
        this.chno = chno;
    }

    public ChoiceQuestion(String chno, String chstem, String chanalysis, Integer chchapter, Integer chanswer, String chA, String chB, String chC, String chD) {
        this.chno = chno;
        this.chstem = chstem;
        this.chanalysis = chanalysis;
        this.chchapter = chchapter;
        this.chanswer = chanswer;
        this.chA = chA;
        this.chB = chB;
        this.chC = chC;
        this.chD = chD;
    }

    public String getChno() {
        return chno;
    }

    public void setChno(String chno) {
        this.chno = chno;
    }

    public String getChstem() {
        return chstem;
    }

    public void setChstem(String chstem) {
        this.chstem = chstem;
    }

    public String getChanalysis() {
        return chanalysis;
    }

    public void setChanalysis(String chanalysis) {
        this.chanalysis = chanalysis;
    }

    public Integer getChchapter() {
        return chchapter;
    }

    public void setChchapter(Integer chchapter) {
        this.chchapter = chchapter;
    }

    public Integer getChanswer() {
        return chanswer;
    }

    public void setChanswer(Integer chanswer) {
        this.chanswer = chanswer;
    }

    public String getChA() {
        return chA;
    }

    public void setChA(String chA) {
        this.chA = chA;
    }

    public String getChB() {
        return chB;
    }

    public void setChB(String chB) {
        this.chB = chB;
    }

    public String getChC() {
        return chC;
    }

    public void setChC(String chC) {
        this.chC = chC;
    }

    public String getChD() {
        return chD;
    }

    public void setChD(String chD) {
        this.chD = chD;
    }

}
