package com.zy.dsdt.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_CLASS.
 */
public class UserClass {

    private String cno;
    private String cname;
    private String cschool;
    private String cteacher;

    public UserClass() {
    }

    public UserClass(String cno) {
        this.cno = cno;
    }

    public UserClass(String cno, String cname, String cschool, String cteacher) {
        this.cno = cno;
        this.cname = cname;
        this.cschool = cschool;
        this.cteacher = cteacher;
    }

    public String getCno() {
        return cno;
    }

    public void setCno(String cno) {
        this.cno = cno;
    }

    public String getCname() {
        return cname;
    }

    public void setCname(String cname) {
        this.cname = cname;
    }

    public String getCschool() {
        return cschool;
    }

    public void setCschool(String cschool) {
        this.cschool = cschool;
    }

    public String getCteacher() {
        return cteacher;
    }

    public void setCteacher(String cteacher) {
        this.cteacher = cteacher;
    }

}
