package com.zy.dsdt.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WRONG_QUESTION.
 */
public class WrongQuestion {

    private String qno;
    private String uno;
    private Integer type;

    public WrongQuestion() {
    }

    public WrongQuestion(String qno) {
        this.qno = qno;
    }

    public WrongQuestion(String qno, String uno, Integer type) {
        this.qno = qno;
        this.uno = uno;
        this.type = type;
    }

    public String getQno() {
        return qno;
    }

    public void setQno(String qno) {
        this.qno = qno;
    }

    public String getUno() {
        return uno;
    }

    public void setUno(String uno) {
        this.uno = uno;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
